project/project/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView
from rest_framework import routers
from simpleapp import views

"""project URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/4.1/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""


router = routers.DefaultRouter()
router.register(r'products', views.ProductViewset)
router.register(r'category', views.CategoryViewset)



urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),  # подключаем встроенные эндопинты для работы с локализацией
    path('admin/', admin.site.urls),
    # path('accounts/', include('django.contrib.auth.urls')),
    path("accounts/", include("allauth.urls")),  # Важен порядок с предыдущим путем
    # path('pages/', include('django.contrib.flatpages.urls')),
   # Делаем так, чтобы все адреса из нашего приложения (simpleapp/urls.py)
   # подключались к главному приложению с префиксом products/.
    path('products/', include('simpleapp.urls')),
    path('swagger-ui/', TemplateView.as_view(
        template_name='swagger-ui.html',
        extra_context={'schema_url': 'openapi-schema'}
    ), name='swagger-ui'),
    # path('', include(router.urls)),
    path('api/', include(router.urls), name='api'),
]

project/simpleapp/models.py
from django.contrib.auth.models import User
from django.core.cache import cache
from django.core.validators import MinValueValidator
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext as _
from django.utils.translation import gettext_lazy   # импортируем «ленивый» геттекст с подсказкой


class Product(models.Model):
    name = models.CharField(
        max_length=50,
        unique=True,  # названия товаров не должны повторяться
        verbose_name=gettext_lazy('Product name'),
        help_text=gettext_lazy('Enter a name of the product'),
    )
    description = models.TextField(
        verbose_name=gettext_lazy('Description'),
        help_text=gettext_lazy('Describe the product'),
    )
    quantity = models.IntegerField(
        validators=[MinValueValidator(0, gettext_lazy('Quantity should be >= 0'))],
        verbose_name=gettext_lazy('Quantity'),
        help_text=gettext_lazy('Quantity should be >= 0'),
    )
    # поле категории будет ссылаться на модель категории
    category = models.ForeignKey(
        to='Category',
        on_delete=models.CASCADE,
        related_name='products',  # все продукты в категории будут доступны через поле products
        verbose_name=gettext_lazy('Category'),
        help_text=gettext_lazy('Choose a category name'),
    )
    price = models.FloatField(
        validators=[MinValueValidator(0.0, gettext_lazy('Price should be >= 0.0'))],
        # verbose_name='Цена',
        verbose_name=gettext_lazy('Price'),
        help_text=gettext_lazy('Price should be >= 0.0'),
    )

    # допишем свойство, которое будет отображать есть ли товар на складе
    @property
    def on_stock(self):
        return self.quantity > 0

    def __str__(self):
        return f'{self.name.title()}: {self.description[:20]}: {self.quantity}'  # title() метод делающий первую букву заглавной

    def get_absolute_url(self):  # добавим абсолютный путь чтобы после создания нас перебрасывало на страницу с товаром
        return reverse('product_detail', args=[str(self.id)])  # f'/products/{self.id}'

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)  # сначала вызываем метод родителя, чтобы объект сохранился
        cache.delete(f'product-{self.pk}')  # затем удаляем его из кэша, чтобы сбросить его

    class Meta:  # Возвращает название категории во множественном или единственном числе в админпанеле
        verbose_name = _('Product')
        verbose_name_plural = _('Products')


# Категория, к которой будет привязываться товар
class Category(models.Model):
    # названия категорий тоже не должны повторяться
    name = models.CharField(
        max_length=100,
        unique=True,
        # verbose_name='Категория'
        verbose_name=gettext_lazy('Category'),
        help_text=gettext_lazy('Category name'),
    )

    def __str__(self):
        return f'{self.name.title()}'

    class Meta:  # Возвращает название категории во множественном или единственном числе в админпанеле
        verbose_name = _('Category')
        verbose_name_plural = _('Categories')


class Subscription(models.Model):
    user = models.ForeignKey(
        to=User,
        on_delete=models.CASCADE,
        related_name='subscriptions',
    )
    category = models.ForeignKey(
        to='Category',
        on_delete=models.CASCADE,
        related_name='subscriptions',
    )

    class Meta:
        verbose_name = _('Subscription')
        verbose_name_plural = _('Subscriptions')

project/templates/product.html
<!--  наследуемся от шаблона default.html, который мы создавали для flatpages -->
{% extends 'flatpages/default.html' %}
{% load i18n %}

<!-- Название у нас будет Product -->
{% block title %}
{% trans 'Product' %}
{% endblock title %}

<!-- В контенте на странице мы выводим сам товар, идентификатор которого был передан в url -->
{% block content %}
<h1>{{ product }}</h1>
{% endblock content %}

project/templates/product_delete.html
<{% extends 'flatpages/default.html' %}
{% load i18n %}

<title>{% trans 'Product deletion' %}</title>
{% block content %}
<h1>{% trans 'Product deletion' %}</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    <p>{% trans 'Delete' %} "{{ object.name }}"?</p>
    <input type="submit" value="Delete" />
</form>
{% endblock content %}

project/templates/product_edit.html
{% extends 'flatpages/default.html' %}
{% load i18n %}

{% block title %}
{% trans 'NewProduct' %}
{% endblock title %}

{% block content %}
<h1>{% trans 'Product' %}</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
</form>
{% endblock content %}

project/templates/product_search.html
{% extends 'flatpages/default.html' %}
{% load i18n %}

<title>{% trans 'Product search' %}</title>

{% block content %}
<form action="" method="get">
        {# Переменная, которую мы передали через контекст, может сгенерировать нам форму с полями #}
        {{ filterset.form.as_p }}
        {# Добавим кнопку отправки данных формы #}
        <input type="submit" value="Найти" />
    </form>
    <hr>
{% if search %}
        <table> <!-- Начинаем описывать таблицу -->
            <tr> <!-- Добавляем строку -->
                <td>{% trans 'Products' %}</td> <!-- Добавляем ячейку в строку -->
                <td>{% trans 'Category' %}</td>
                <td>{% trans 'Description' %}</td>
                <td>{% trans 'Price' %}</td>
            </tr>

            {% for product in search %}
            <tr>
                <td>{{ product.name }}</td>
                <td>{{ product.category }}</td>
                <td>{{ product.description|truncatechars:20 }}</td>
                <td>{{ product.price }}</td>
                <td>{{ product.price__gt }}</td>
                <td>{{ product.price__lt }}</td>
            </tr>
            {% endfor %}
        </table>

    {% else %}

        <h2>{% trans 'No such product' %}</h2>
    {% endif %}
{% endblock content %}

project/templates/products.html
<!--  наследуемся от шаблона default.html, который мы создавали для flatpages -->
{% extends 'flatpages/default.html' %}

{% load custom_filters %} <!-- Подключаем фильтр из custom_filters -->
{% load custom_tags %} <!-- Подключаем таг из custom_tags -->
{% load cache %} <!--Кэширование -->
{% load i18n %}
<!-- Название у нас будет products -->
{% block title %}
{% trans 'Products' %}
{% endblock title %}

<!-- В контенте на странице мы выводим все товары -->
{% block content %}
    {% cache 30 header %}
    <h1>{% trans 'All goods' %}</h1>
    <!-- Используем переданную из представления переменную time_now
    и применяем к ней фильтр date. По назначению этот фильтр очень похож
    на метод strftime у объекта datetime в Python — вывод времени
    в указанном формате. -->
<!--    <h3>{{ time_now|date:'M d Y' }}</h3>-->
<!--    так было-->
    <h3>{% current_time '%b %d %Y' %}</h3>
<!--так стало с новым тегом, которы мы подключили выше-->

    <!--Добавляем форму, которая объединяет набор полей, которые будут отправляться в запросе -->
    <!-- <form action="" method="get" >
    {{ filterset.form.non_field_errors }}

    {{ filterset.form.name__icontains.errors }}
    <label for="{{ filterset.form.name__icontains.id_for_label }}">Search</label>
    <input
        id="{{ filterset.form.name__icontains.id }}"
        name="{{ filterset.form.name__icontains.name }}"
        value="{{ filterset.form.name__icontains.value }}"
        class="form-control"
    >
    <input type="submit" class="mt-3 btn-primary" value="Найти" />
    </form> -->
<!--    <form action="" method="get">-->
<!--       {# Переменная, которую мы передали через контекст, может сгенерировать нам форму с полями #}-->
<!--       {{ filterset.form.as_p }}-->
<!--       {# Добавим кнопку отправки данных формы #}-->
<!--       <input type="submit" value="Найти" />-->
<!--    </form> &lt;!&ndash; был поиск таков&ndash;&gt;-->

<!--    <h3> {{ next_sale|default_if_none:"Чуть позже сообщим о распродаже!" }} </h3>-->
    <!-- Если в переменной next_sale будет None,
    то выведется указанный в фильтре текст -->
    <hr>
    {% endcache %}
    <a href="{% url 'subscriptions' %}">{% trans 'Subscribe' %}</a>
    {# Теперь будем проверять не request.user.is_authenticated, а конкретные права #}
    {% if perms.simpleapp.add_product %}
    <a href="{% url 'product_create' %}">{% trans 'Add product' %}</a>
    {% endif %}

    {% if products %}
        <table> <!-- Начинаем описывать таблицу -->
            <tr> <!-- Добавляем строку -->
                <td>{% trans 'Products' %}</td> <!-- Добавляем ячейку в строку -->
                <td>{% trans 'Description' %}</td>
                <td>{% trans 'Category' %}</td>
                <td>{% trans 'Price' %}</td>
                <td>{% trans 'Quantity' %}</td>

                {# Условие получается составным. #}
                {% if perms.simpleapp.change_product or perms.simpleapp.delete_product %}
                <td>{% trans 'Options' %}</td>
                {% endif %}
            </tr> <!-- Не забываем закрыть HTML-тег строки -->
                <!-- Для каждого товара будете генерироваться новая строчка,
                т.е. новый HTML код, который указан в теле цикла.
                При этом сам цикл работает точно так же, как и в Python.
                 product — переменная цикла, т.е. наш товар полученный из списка -->
            {% for product in products %}
                <!-- Не забываем, что переменные в шаблоне ничем не отличаются
                от переменных в Python. Здесь также можно получать доступ к
                полям объекта модели. Например, здесь мы выводим имя,
                в следующем столбце описание, и т.д.  -->
                    <td>{{ product.name }}</td>
                    <td>{{ product.description|truncatewords:2 }}</td>
                    <!-- Добавим специальный фильтр truncatechars,
                    чтобы ограничить количество символов до 15.
                    Все остальные символы превратятся в многоточие. -->
                    <td>{{ product.category.name }}</td>
                    <!-- Используем наш фильтр -->
                    <td>{{ product.price|currency:"usd" }}</td>
                    <td>{{ product.quantity }}</td>
                    <td>
                        {# А здесь доступ для каждой ссылки теперь будем проверять отдельно #}
                        {% if perms.simpleapp.change_product %}
                        <a href="{% url 'product_update' pk=product.id %}">{% trans 'Change' %}</a>
                        {% endif %}
                        {% if perms.simpleapp.delete_product %}
                        <a href="{% url 'product_delete' product.id %}">{% trans 'Delete' %}</a>
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}

        </table>
    {% else %}
        <h2>{% trans 'There are no any goods' %}</h2>
    {% endif %}

{# Добавляем пагинацию на страницу #}
    {# Информация о предыдущих страницах #}
    {% if page_obj.has_previous %}
    {# Для каждой ссылки пагинации указываем обработку через новый тег #}
        <a href="?{% url_replace page=1 %}">1</a> <!-- Так стало -->
        <!-- <a href="?page=1">1</a> так было-->
        {% if page_obj.previous_page_number != 1 %}
            ...
            <a href="?{% url_replace page=page_obj.previous_page_number %}">{{ page_obj.previous_page_number }}</a> <!-- Так стало -->
            <!-- <a href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a> так было-->
        {% endif %}
    {% endif %}

    {# Информация о текущей странице #}
    {{ page_obj.number }}

    {# Информация о следующих страницах #}
    {% if page_obj.has_next %}
        <a href="?{% url_replace page=page_obj.next_page_number %}">{{ page_obj.next_page_number }}</a> <!-- Так стало -->
        <!-- <a href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a> так было-->
        {% if paginator.num_pages != page_obj.next_page_number %}
            ...
            <a href="?{% url_replace page=page_obj.paginator.num_pages %}">{{ page_obj.paginator.num_pages }}</a> <!-- Так стало -->
            <!-- <a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a> так было-->
        {% endif %}
    {% endif %}
{% endblock content %}
</html>

project/templates/subscriptions.html
{% extends 'flatpages/default.html' %}
{% load i18n %}

{% block title %}
{% trans 'Subscriptions' %}
{% endblock title %}

{% block content %}
    {% for category in categories  %}
        <p>
            {{ category.name }}
            <form method="post">
                {% csrf_token %}
                <input type="hidden" name="category_id" value="{{ category.id }}" />

                {% if category.user_subscribed %}
                    <button disabled>{% trans 'Subscribe' %}</button>
                    <button name="action" value="unsubscribe">{% trans 'Unsubscribe' %}</button>
                {% else %}
                    <button name="action" value="subscribe">{% trans 'Subscribe' %}</button>
                    <button disabled>{% trans 'Unsubscribe' %}</button>
                {% endif %}
            </form>
        </p>
    {% endfor %}
{% endblock content %}

project/templates/swagger-ui.html
<!DOCTYPE html>
<html>
 <head>
   <title>Swagger</title>
   <meta
charset="utf-8"/>
   <meta name="viewport" content="width=device-width, initial-scale=1">
   <link rel="stylesheet" type="text/css" href="//unpkg.com/swagger-ui-dist@3/swagger-ui.css" />
 </head>
 <body>
   <div id="swagger-ui"></div>
   <script src="//unpkg.com/swagger-ui-dist@3/swagger-ui-bundle.js"></script>
   <script>
   const ui = SwaggerUIBundle({
       url: "/static/openapi-schema.yml",
       dom_id: '#swagger-ui',
       presets: [
         SwaggerUIBundle.presets.apis,
         SwaggerUIBundle.SwaggerUIStandalonePreset
       ],
       layout: "BaseLayout",
       requestInterceptor: (request) => {
         request.headers['X-CSRFToken'] = "{{ csrf_token }}"
         return request;
       }
     })
   </script>
 </body>
</html>